# Kafka Configuration
kafka.bootstrap.servers=
kafka.topic.name=
kafka.consumer.group.id=

# AWS Configuration
aws.region=
aws.access.key.id=
aws.secret.access.key=

# S3 Configuration
s3.bucket.name=
s3.key.prefix=

# Spark Configuration
spark.app.name=KafkaSparkS3Integration
spark.master.uri=local[*]